using System.Collections.Generic;
using LlmTornado.Audio.Models.Zai;
using Newtonsoft.Json;

namespace LlmTornado.Audio.Vendors.Zai
{
    /// <summary>
    /// Z.AI audio transcription request DTO.
    /// </summary>
    internal class VendorZaiAudioRequest
    {
        /// <summary>
        /// The model ID to invoke.
        /// </summary>
        [JsonProperty("model")]
        public string Model { get; set; } = AudioModelZaiAsr.ModelGlmAsr2512.Name;

        /// <summary>
        /// Base64 encoded audio file.
        /// </summary>
        [JsonProperty("file_base64", NullValueHandling = NullValueHandling.Ignore)]
        public string? FileBase64 { get; set; }

        /// <summary>
        /// In long text scenarios, you can provide previous transcription results as context.
        /// Recommended to be less than 8000 characters.
        /// </summary>
        [JsonProperty("prompt", NullValueHandling = NullValueHandling.Ignore)]
        public string? Prompt { get; set; }

        /// <summary>
        /// Hotword list to improve recognition accuracy for domain-specific vocabulary.
        /// Recommended not to exceed 100 items.
        /// </summary>
        [JsonProperty("hotwords", NullValueHandling = NullValueHandling.Ignore)]
        public List<string>? Hotwords { get; set; }

        /// <summary>
        /// Whether to stream the response.
        /// </summary>
        [JsonProperty("stream")]
        public bool Stream { get; set; }

        /// <summary>
        /// Unique request ID for tracking.
        /// </summary>
        [JsonProperty("request_id", NullValueHandling = NullValueHandling.Ignore)]
        public string? RequestId { get; set; }

        /// <summary>
        /// Unique ID of the end-user for abuse monitoring.
        /// </summary>
        [JsonProperty("user_id", NullValueHandling = NullValueHandling.Ignore)]
        public string? UserId { get; set; }

        /// <summary>
        /// Creates a Z.AI audio request from a TranscriptionRequest.
        /// </summary>
        public static VendorZaiAudioRequest FromRequest(TranscriptionRequest request)
        {
            VendorZaiAudioRequest zaiRequest = new VendorZaiAudioRequest
            {
                Model = request.Model?.Name ?? AudioModelZaiAsr.ModelGlmAsr2512.Name,
                Prompt = request.Prompt,
                Stream = request.Stream ?? false
            };

            // Apply Zai-specific extensions
            if (request.ZaiExtensions is not null)
            {
                TranscriptionRequestZaiExtensions ext = request.ZaiExtensions;

                if (ext.Hotwords is { Count: > 0 })
                {
                    zaiRequest.Hotwords = ext.Hotwords;
                }

                if (!string.IsNullOrEmpty(ext.RequestId))
                {
                    zaiRequest.RequestId = ext.RequestId;
                }

                if (!string.IsNullOrEmpty(ext.UserId))
                {
                    zaiRequest.UserId = ext.UserId;
                }

                if (!string.IsNullOrEmpty(ext.FileBase64))
                {
                    zaiRequest.FileBase64 = ext.FileBase64;
                }
            }

            return zaiRequest;
        }
    }

    /// <summary>
    /// Z.AI audio transcription response DTO.
    /// </summary>
    internal class VendorZaiAudioResponse
    {
        /// <summary>
        /// Task ID.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Request creation time, as a Unix timestamp in seconds.
        /// </summary>
        [JsonProperty("created")]
        public long? Created { get; set; }

        /// <summary>
        /// Request ID passed by the client or generated by the platform.
        /// </summary>
        [JsonProperty("request_id")]
        public string? RequestId { get; set; }

        /// <summary>
        /// Model name.
        /// </summary>
        [JsonProperty("model")]
        public string? Model { get; set; }

        /// <summary>
        /// The complete transcribed content of the audio.
        /// </summary>
        [JsonProperty("text")]
        public string? Text { get; set; }
    }

    /// <summary>
    /// Z.AI audio transcription stream response DTO.
    /// </summary>
    internal class VendorZaiAudioStreamResponse
    {
        /// <summary>
        /// Task ID.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Request creation time, as a Unix timestamp in seconds.
        /// </summary>
        [JsonProperty("created")]
        public long? Created { get; set; }

        /// <summary>
        /// Model name.
        /// </summary>
        [JsonProperty("model")]
        public string? Model { get; set; }

        /// <summary>
        /// Audio transcription event type: transcript.text.delta or transcript.text.done.
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; }

        /// <summary>
        /// Incremental audio transcription information returned by the model.
        /// </summary>
        [JsonProperty("delta")]
        public string? Delta { get; set; }

        /// <summary>
        /// Complete text (used with transcript.text.done).
        /// </summary>
        [JsonProperty("text")]
        public string? Text { get; set; }
    }
}
