using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace LlmTornado.Files
{
    /// <summary>
    /// Source of the file.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TornadoFileSource
    {
        /// <summary>
        /// File uploaded by user.
        /// </summary>
        [EnumMember(Value = "upload")]
        Upload,

        /// <summary>
        /// File from repository.
        /// </summary>
        [EnumMember(Value = "repository")]
        Repository,

        /// <summary>
        /// File generated by Mistral.
        /// </summary>
        [EnumMember(Value = "mistral")]
        Mistral
    }
}
